<?php

namespace App\Controller\Api;

use App\Controller\AppController;
use Cake\Event\EventInterface;
use Firebase\JWT\JWT;

class AuthController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Authentication->allowUnauthenticated(['signup', 'login']);
    }

    public function login(){
        $result = $this->Authentication->getResult();
        if ($result->isValid()) {
            $privateKey = file_get_contents(CONFIG . '/jwt.key');
            $user = $result->getData();
            $payload = [
                'iss' => 'recipe-api',
                'sub' => $user->id,
                'exp' => time() + 3600,
            ];
            $code = 200;
            $json = [
                'token' => JWT::encode($payload, $privateKey, 'RS256'),
            ];
        } else {
            $code = 401;
            $json = [$result->getStatus() => $result->getErrors()];
        }
        return $this->json($json, $code);
    }

    public function signup(){
        $this->getRequest()->allowMethod('post');
        $user = $this->fetchTable('Users')->newEntity($this->getRequest()->getData());
        $user->is_active = true;
        try{
            $this->fetchTable('Users')->save($user);
            return $this->json([
                'success' => true,
                'user' => $user,
            ]);
        } catch (\Exception $e){
            return $this->json([
                'success' => false,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
